repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: clean_pycache
        name: "Clean PyCache"
        entry: bash ./scripts/clean_pycache.sh
        language: system
        always_run: true


  - repo: local
    hooks:
      - id: create_tree
        name: "Create tree"
        entry: bash ./scripts/create_tree.sh
        language: system
        always_run: true